### ISSUE TITLE
Missing snprintf and vsnprintf

### ISSUE THREAD

**Issue by glebm** [pspdev/newlib#2]
Needed for DevilutionX (Diablo 1)

/cc @AJenbo @sajattack

**Comment by glebm** [comment]
Strange, I see it here in the 3.3.0 branch <https://github.com/pspdev/newlib/blob/7b50ff4d76f58e26fb33f6a4ea5f3a067ffe95be/newlib/libc/sys/psp/xprintf.c#L705>

**Comment by glebm** [comment]
And also in the 1.20 branch:

https://github.com/pspdev/newlib/blob/6dc26bb7f8bdc7dff72a811104e1d654d77f75d9/newlib/libc/sys/psp/xprintf.c#L705

**Comment by sajattack** [comment]
truncate is here too, not sure what these `#ifdef`s are about https://github.com/pspdev/newlib/blob/7b50ff4d76f58e26fb33f6a4ea5f3a067ffe95be/newlib/libc/sys/psp/libcglue.c#L697

**Comment by sajattack** [comment]
Did a quick check with ghidra and my libc.a contained these *printfs, not sure why the linker wasn't finding them.

**Comment by frabert** [comment]
Has anybody had any luck in solving this one? I too am having issues compiling stuff that uses `pspDebugScreenPrintf` because it references `vsnprintf`, even though I can definitely see it if I `psp-readelf -s /usr/local/pspdev/psp/lib/libc.a | grep 'vsnprintf'`

**Comment by sajattack** [comment]
Apparently @fjtrujy is on the case.

**Comment by fjtrujy** [comment]
Yes, it has been implemented, in the latest version 4.1.0, closing issue
